security:
    role_hierarchy:

        ROLE_SFS_CMS_ADMIN_SECTIONS_RO:
            - PERMISSION_SFS_CMS_ADMIN_SECTION_LIST
            - PERMISSION_SFS_CMS_ADMIN_SECTION_READ
            - PERMISSION_SFS_CMS_ADMIN_SECTION_PREVIEW
            - PERMISSION_SFS_CMS_ADMIN_SECTION_VERSIONS
            - PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_EXPORT
        ROLE_SFS_CMS_ADMIN_SECTIONS_CREATOR:
            - ROLE_SFS_CMS_ADMIN_SECTIONS_RO
            - PERMISSION_SFS_CMS_ADMIN_SECTION_CREATE
            - PERMISSION_SFS_CMS_ADMIN_SECTION_IMPORT
            - PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_IMPORT
            - PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_CREATE
        ROLE_SFS_CMS_ADMIN_SECTIONS_PUBLISHER:
            - ROLE_SFS_CMS_ADMIN_SECTIONS_CREATOR
            - PERMISSION_SFS_CMS_ADMIN_SECTION_DUPLICATE
            - PERMISSION_SFS_CMS_ADMIN_SECTION_UPDATE
            - PERMISSION_SFS_CMS_ADMIN_SECTION_ROUTES
            - PERMISSION_SFS_CMS_ADMIN_SECTION_DELETE
            - PERMISSION_SFS_CMS_ADMIN_SECTION_UNPUBLISH
            - PERMISSION_SFS_CMS_ADMIN_SECTION_CLEANUP_VERSIONS
            - PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_KEEP
            - PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_PUBLISH
            - PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_INFO
            - PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_RECOMPILE
            - PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_CLEAR_COMPILED
            - PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_DELETE
        ROLE_SFS_CMS_ADMIN_SECTIONS_RW:
            - ROLE_SFS_CMS_ADMIN_SECTIONS_PUBLISHER

